name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Build Project
      run: python -m compileall levelz
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Sphinx
      run: |
        pip install -U sphinx
        pip install sphinx-autoapi sphinx-favicon
    - name: Build Docs
      run: sphinx-build docs docs/build
    - name: Deploy Docs
      run: bash sphinx.sh ${GITHUB_SHA::7}
